jobs:
  - name: terraform-aws-dataworks-htme-pr
    max_in_flight: 1
    plan:
      - get: terraform-aws-dataworks-htme-pr
        trigger: true
        version: every
      - put: terraform-aws-dataworks-htme-pr
        params:
          path: terraform-aws-dataworks-htme-pr
          status: pending
      - .: (( inject meta.plan.linting-shell ))
        input_mapping:
          terraform-aws-dataworks-htme: terraform-aws-dataworks-htme-pr
        on_failure:
          put: terraform-aws-dataworks-htme-pr
          params:
            path: terraform-aws-dataworks-htme-pr
            status: failure
      - .: (( inject meta.plan.terraform-fmt ))
        input_mapping:
          terraform-aws-dataworks-htme: terraform-aws-dataworks-htme-pr
        on_failure:
          put: terraform-aws-dataworks-htme-pr
          params:
            path: terraform-aws-dataworks-htme-pr
            status: failure
      - .: (( inject meta.plan.terraform-validate ))
        input_mapping:
          terraform-aws-dataworks-htme: terraform-aws-dataworks-htme-pr
        on_failure:
          put: terraform-aws-dataworks-htme-pr
          params:
            path: terraform-aws-dataworks-htme-pr
            status: failure
        on_success:
          put: terraform-aws-dataworks-htme-pr
          params:
            path: terraform-aws-dataworks-htme-pr
            status: success