jobs:
- name: test
  plan:
  - get: terraform-aws-dataworks-htme
    trigger: true
    version: every
  - .: (( inject meta.plan.terraform-bootstrap ))
    input_mapping:
      terraform-aws-dataworks-htme: terraform-aws-dataworks-htme
  - task: terraform-terratest
    .: (( inject meta.plan.terraform-terratest ))
    input_mapping:
      terraform-aws-dataworks-htme: terraform-aws-dataworks-htme
  .: (( inject meta.plan.notify ))
