jobs:
- name: test
  plan:
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 2d9ad68 (chore: fixing missing concource gets)
  - get: htme-release
    trigger: true
    version: every
  - get: dw-al2-hardened-ami
    trigger: true
    version: every
<<<<<<< HEAD
=======
>>>>>>> e01d0ff (Dtwrks 849 (#8))
=======
>>>>>>> 2d9ad68 (chore: fixing missing concource gets)
  - get: terraform-aws-dataworks-htme-test
    trigger: true
    version: every
  - get: terraform-aws-dataworks-htme
  - put: terraform-aws-dataworks-htme-test
    params:
      repository: terraform-aws-dataworks-htme
      merge: true
  - .: (( inject meta.plan.terraform-bootstrap ))
    input_mapping:
      terraform-aws-waf: terraform-aws-dataworks-htme-test
  - task: terraform-terratest
    .: (( inject meta.plan.terraform-terratest ))
    input_mapping:
      terraform-aws-waf: terraform-aws-dataworks-htme-test
  - put: terraform-aws-dataworks-htme
    params:
      repository: terraform-aws-dataworks-htme-test
      merge: true
  .: (( inject meta.plan.notify ))
