jobs:
- name: test
  plan:
  - get: dw-al2-hardened-ami
    trigger: true
    version: every
  - get: terraform-aws-dataworks-htme-test
    trigger: true
    version: every
  - get: terraform-aws-dataworks-htme
  - get: aws-management-infrastructure
  - .: (( inject meta.plan.terraform-output-management ))
  - .: (( inject meta.plan.get-artefacts ))
    config:
      params:
        AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
        AWS_ACC: ((aws_account.management))
  - put: terraform-aws-dataworks-htme-test
    params:
      repository: terraform-aws-dataworks-htme
      merge: true
  - .: (( inject meta.plan.terraform-bootstrap ))
    input_mapping:
      terraform-aws-dataworks-htme: terraform-aws-dataworks-htme-test
  - task: terraform-terratest
    .: (( inject meta.plan.terraform-terratest ))
    input_mapping:
      terraform-aws-dataworks-htme: terraform-aws-dataworks-htme-test
  - put: terraform-aws-dataworks-htme
    params:
      repository: terraform-aws-dataworks-htme-test
      merge: true
  .: (( inject meta.plan.notify ))
